### ISSUE TITLE
Melpa package?

### ISSUE THREAD

**Issue by priyadarshan** [hatschipuh/better-helm#5]
`better-helm` works wonderfully. It is exactly the kind of experience I was hoping to find in `helm`. 

Frankly, without it I would have dropped using `helm` for good.

Is there a way to make it a proper little package, perhaps available on Melpa?

I am sure many users would like to try it and quite a few will adopt it, as it sports a very balanced "sane behaviour" use-case.

Thank you so much for putting it together.

**Comment by priyadarshan** [comment]
By the way, with `use-package` I can load the whole `better-helm.el` with no slowdown at all. My Emacs starts in less than half a second currently.

```
  (use-package better-helm
    :load-path "site-lisp"
    :defer 2
    :diminish helm-mode
    :config
    (bind-key "M-x" 'helm-M-x)
    (bind-key "C-x C-f" 'helm-find-files))
```

**Comment by alphapapa** [comment]
@priyadarshan What `better-helm.el` file are you referring to?  All I see in this repo is a screenshot and a readme.

**Comment by priyadarshan** [comment]
For my own use, I just put together all the snippets in one file, to load them all at once. It is here: https://gist.github.com/priyadarshan/c0545bfcf6e32b3730688bd5d072e175
It is better to refer to the original better-helm repo of course.

**Comment by alphapapa** [comment]
Ah, I see.  Well, putting it on MELPA is an interesting idea, but I would recommend against doing it as a package named `better-helm`.  To me that strongly suggests a fork of Helm, which this isn't.  Maybe something like `helm-easy-defaults` or something that clearly indicates that it's only configuration.

Of course, then you have to consider that it could become out-of-sync with Helm and break.  And people who start using it and then want to customize things might get into trouble with conflicting options.  This is what Emacs' `customize` API is designed to handle, but it doesn't support configuring the defaults of another package.  I don't know, maybe you could hack something together that only changed certain settings if they weren't changed from the Helm defaults, but you'd probably run into issues with certain changes not taking effect until Emacs is restarted, or messy things like that.

So it might work, but I'm not sure it's a good idea.

**Comment by priyadarshan** [comment]
`helm-easy-defaults` sounds like a nice name. Perhaps, just having all the snippets in one file would suffice, by making it easier for people to use?
Or at least, if the babel-blocks would have `:tangle yes` option, one could tangle the org-mode file to an elisp file, ready to be used.

I do not mind doing it once or a few times, but, as this current repository will hopefully evolve, it would be nice to have a way to track it without manually copying all the snippets.

Thanks!

**Comment by clemera** [comment]
Thanks for your suggestions @alphapapa, @priyadarshan.

Happy to hear that this guide is useful for some people. Adding the tangle option to produce a standalone emacs-lisp file is a nice idea. I just updated the repo accordingly and renamed it to `helm-better-defaults` because there is already a `better-defaults` package I know of which just installs configurations, too. So having a similar name might be a good idea. 

I'm not experienced with adding stuff to melpa but I will look into that in the near future.
If you have further suggestions/issues let me know.

**Comment by priyadarshan** [comment]
Thank you for adding tangle option.
To submit to Melpa is not too dificult: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md
Thanks!

**Comment by alphapapa** [comment]
@hatschipuh Cool!

My best advice about packaging for MELPA, besides reading all the docs, is to make extensive use of the `make sandbox` tool.  If your package installs cleanly and works there, you can be pretty sure it will work for everyone else.  And when testing a new version, just delete the sandbox directory and run the command to get a new one.

**Comment by clemera** [comment]
The guide got some updates. If you want to activate it now you have to call `(helm-ido-like)` after
require it. I'm not sure if I should make it a package, because it's more a bunch of hacks and installations recommendations. I think it is better to leave it as a guide. With the tangled file it's easy for users to load everything in it.
