### ISSUE TITLE
helm smex problem. (when candicate not exist my choice, how to use input content)

### ISSUE THREAD

**Issue by zw963** [hatschipuh/better-helm#6]
Hi, i try to switch from smex to this helm frontend version.

But, exist a problem i want to consider.
Hi, when worked with smex,  in some case, some command
not exist in my candidate list. (especial very simple command)

e.g.  M-x pp, the first match is:   `pr-ps-name`.
in this case, if use with ido, i will run `ido-select-text`.
just sent out what i input to minibuffer, it worked.

If use with helm, how to do this? Thanks.

**Comment by zw963** [comment]
Another question, does you plan to extract `helm-smex` into one package to ELPA?

If you don't have any plan, I will try do this.

thanks.

**Comment by clemera** [comment]
The problem is possibly that you have loaded the commands that are missing after helm-smex? You can call helm-smex with prefix argument `C-u` to reload the candidates list. Does this fix your problem?

I'm not sure how to replicate the behaviour you get with `ido-select-text`. What are you trying to match with pp? You can insert a space after the search term to get candidates not matched with flx if that does help?

I plan to release the configurations as a package to MELPA. Having a standalone package for helm-smex might be a good idea. If you would like to do it great! But I think you have to use MELPA, helm is not part of ELPA.

**Comment by zw963** [comment]
Sorry for confuse..

> > You can call helm-smex with prefix argument C-u to reload the candidates list. Does this fix your problem?

Not worked. C-u M-x, still keep pr-ps-name at the first.

> > What are you trying to match with pp?

What I want to matched is `pp` itself. (pp is a debug command in lisp)

> > You can insert a space after the search term to get candidates not matched with flx if that does help?

No, after insert a space, the first candicate still `pr-ps-name`. 

> > If you would like to do it great! But I think you have to use MELPA, helm is not part of ELPA.

I will have a try recent days if you have no time to do this.

**Comment by clemera** [comment]
I checked and pp seems to be a function not a command, helm-smex is only for invoking commands. I still do not really understand what your trying to achieve with ido-select-text?

**Comment by zw963** [comment]
> > I checked and pp seems to be a function not a command, helm-smex is only for invoking commands.

you are right, sorry for unsuitabe example.

maybe this is a unexist issue ... sorry. : )

**Comment by zw963** [comment]
Hi, just want you to know, there exist a [helm-smex](https://github.com/ptrv/helm-smex) package,
it worked well for me.

And, more, this issue is created because current code exist bug.

we have to add following code into `helm-smex/run`.

``` cl
(and smex-auto-update
       (smex-detect-new-commands)
       (smex-update))
```

other, if you load a new package after start up emacs, those command not exist
in helm-smex at all. you have to run `(smex-update)` to update command index.

**Comment by zw963** [comment]
Fine, I see you add `helm-smex` as dependency.
anywhy, the problem is gone.
